name: serverless_dart_example
description: A sample Serverless / Google Cloud Function / Dart function
version: 0.0.1
author: Paul Reimer <paul@p-rimes.net>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  node_interop: ^1.0.0-dev.7.0

dev_dependencies:
  test: ^0.12.30
  build_node_compilers: ^0.1.2
  build_runner: any
  build_test: any
